#!/bin/bash
set -x
cd $OPENSHIFT_REPO_DIR
export GRADLE_USER_HOME=$OPENSHIFT_DATA_DIR/gradle
export GRADLE_HOME=$OPENSHIFT_DATA_DIR/gradle-1.6
export PATH=$GRADLE_HOME/bin:$PATH

gradle server.webapp:war
gradle server.war:war

cp server.webapp/build/libs/angular-webapp.war ./app-root/runtime/dependencies/jbossews/webapps/ROOT.war
cp server.war/build/libs/angular-rest.war ./app-root/runtime/dependencies/jbossews/webapps/angular-rest.war
