#!/bin/bash
echo "Checking Gradle ..." 
set -x
if [ ! -d $OPENSHIFT_DATA_DIR/gradle-1.6 ]
then
    echo "Gradle not found downloading ..." 
    cd $OPENSHIFT_DATA_DIR
    mkdir gradle
    wget http://services.gradle.org/distributions/gradle-1.6-bin.zip
    unzip gradle-1.6-bin.zip
    rm -f gradle-1.6-bin.zip
fi
echo "Gradle done ..."
